export const BILLING_PLANS = [
  {
    id: 'essential_monthly',
    tier: 'Essencial',
    name: 'Basico',
    interval: 'month',
    label: 'Mensal',
    amountInCents: 14900,
    support: 'Email',
    description: 'Para o pequeno produtor que quer sair do papel.',
    recommended: false,
    includesPrevious: false,
    inheritedFeatureCount: 0,
    features: [
      'Cadastro e rastreabilidade limitada',
      'Importacao via CSV com 35 campos',
      'Genealogia completa',
      'Manejo sanitario e vacinas',
      'Suporte por email',
    ],
  },
  {
    id: 'performance_monthly',
    tier: 'Performance',
    name: 'Pro',
    interval: 'month',
    label: 'Mensal',
    amountInCents: 38900,
    support: 'WhatsApp',
    description: 'Para operacoes que buscam ROI com reproducao e GMD.',
    recommended: true,
    includesPrevious: true,
    inheritedFeatureCount: 4,
    features: [
      'Cadastro e rastreabilidade ilimitada',
      'Importacao via CSV com 35 campos',
      'Genealogia completa',
      'Manejo sanitario e vacinas',
      'Modulo reprodutivo / IATF',
      'Pesagem e historico de GMD',
      'Gestao de custos por lote',
      'Fluxo de caixa e DRE basico',
      'Suporte por WhatsApp',
    ],
  },
  {
    id: 'enterprise_monthly',
    tier: 'Empresarial',
    name: 'Premium',
    interval: 'month',
    label: 'Mensal',
    amountInCents: 89900,
    support: 'Consultivo 24/7',
    description: 'Para gestao agroindustrial com controle contabil completo.',
    recommended: false,
    includesPrevious: true,
    inheritedFeatureCount: 9,
    features: [
      'Cadastro e rastreabilidade ilimitada',
      'Importacao via CSV com 35 campos',
      'Genealogia completa',
      'Manejo sanitario e vacinas',
      'Modulo reprodutivo / IATF',
      'Pesagem e historico de GMD',
      'Gestao de custos por lote',
      'Fluxo de caixa e DRE basico',
      'Suporte por WhatsApp',
      'Fluxo de caixa e DRE completo',
      'Multi-fazendas / multi-tenant',
      'Integracao com sensores IoT',
      'IA preditiva para tendencia de peso',
      'Suporte consultivo 24/7',
    ],
  },
  {
    id: 'essential_yearly',
    tier: 'Essencial',
    name: 'Basico',
    interval: 'year',
    label: 'Anual',
    amountInCents: 178800,
    support: 'Email',
    description: 'Para o pequeno produtor que quer sair do papel.',
    recommended: false,
    includesPrevious: false,
    inheritedFeatureCount: 0,
    features: [
      'Cadastro e rastreabilidade limitada',
      'Importacao via CSV com 35 campos',
      'Genealogia completa',
      'Manejo sanitario e vacinas',
      'Suporte por email',
    ],
  },
  {
    id: 'performance_yearly',
    tier: 'Performance',
    name: 'Pro',
    interval: 'year',
    label: 'Anual',
    amountInCents: 466800,
    support: 'WhatsApp',
    description: 'Para operacoes que buscam ROI com reproducao e GMD.',
    recommended: true,
    includesPrevious: true,
    inheritedFeatureCount: 4,
    features: [
      'Cadastro e rastreabilidade ilimitada',
      'Importacao via CSV com 35 campos',
      'Genealogia completa',
      'Manejo sanitario e vacinas',
      'Modulo reprodutivo / IATF',
      'Pesagem e historico de GMD',
      'Gestao de custos por lote',
      'Fluxo de caixa e DRE basico',
      'Suporte por WhatsApp',
    ],
  },
  {
    id: 'enterprise_yearly',
    tier: 'Empresarial',
    name: 'Premium',
    interval: 'year',
    label: 'Anual',
    amountInCents: 1078800,
    support: 'Consultivo 24/7',
    description: 'Para gestao agroindustrial com controle contabil completo.',
    recommended: false,
    includesPrevious: true,
    inheritedFeatureCount: 9,
    features: [
      'Cadastro e rastreabilidade ilimitada',
      'Importacao via CSV com 35 campos',
      'Genealogia completa',
      'Manejo sanitario e vacinas',
      'Modulo reprodutivo / IATF',
      'Pesagem e historico de GMD',
      'Gestao de custos por lote',
      'Fluxo de caixa e DRE basico',
      'Suporte por WhatsApp',
      'Fluxo de caixa e DRE completo',
      'Multi-fazendas / multi-tenant',
      'Integracao com sensores IoT',
      'IA preditiva para tendencia de peso',
      'Suporte consultivo 24/7',
    ],
  },
] as const;

export type BillingPlanId = (typeof BILLING_PLANS)[number]['id'];

export function getBillingPlan(planId: string) {
  return BILLING_PLANS.find((plan) => plan.id === planId);
}
